config/routes.rb
Rails.application.routes.draw do
  root "blogs#index"
  resources :blogs
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_bottom_bar.html.erb
<style>
p {
    text-align: center;
}
</style>

<p> crusty_bobe | github.com/crustyBobe </p>

app/views/blogs/_form.html.erb
<%= render 'navbar' %>

<style>
h1 {text-align: center;}
div {text-align: center;}

body {
  padding-top: 60px;
  background: #EBFBFF;
}
</style>

<body>
  <%= form_with(model: blog, local: true) do |form| %>
    <% if blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <h2> Blog Title </h2>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <h2> Blog Descrpition </h2>
      <%= form.text_area :description %>
    </div>

    <div class="actions">
      <input type="submit" class="btn btn-secondary" value="Update">
    </div>
  <% end %>
</body>

app/views/blogs/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to "Home", href="/", class: "btn btn-danger"%>
    
    <% if admin_signed_in? %>
        <%= button_to "Log Out", destroy_admin_session_path, method: :delete, class: "btn btn-danger ml-3"%>
        <%= link_to 'New Project', new_blog_path, class: "btn btn-danger ml-3"%>
    <%end%>
    <% if !admin_signed_in? %>
        <%= button_to "Sign In", href="/admins/sign_in", class: "btn btn-danger ml-3"%>
    <%end%>
</nav>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= render 'bottom_bar'%>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'navbar'%>

<style>

h1 {text-align: center;}
h3 {text-align: center;}
tr {text-align: center;}
body {padding-top: 40px;}

#blog {
  width: 850px;
  margin: auto;
  border: 10px solid;
  margin-top: 25px;
  margin-bottom: 25px;
  background: #4046FF;
}

#blogs {
  background: #EBFBFF;
}

</style>

<body id='blogs'>
  <div id='heading'>
    <h1>Posts</h1>
  </div>
    <% @blogs.each do |blog| %>
      <div id='blog'>
        <h3><%= blog.title %></h3>
        <p>
          <a class="btn btn-secondary"<%= link_to 'Show', blog%></a>

          <% if admin_signed_in? %>
            <a class="btn btn-secondary"<%=link_to 'Edit', edit_blog_path(blog)%></a>
        <% end %>
        </p>
      </div>
    <% end %>
</body>

<%= render 'bottom_bar'%>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= render 'bottom_bar'%>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'navbar' %>

<style>

h1 {text-align: center;}

body {padding-top: 40px;}

h1 {text-align: center;}

body {
  background: #EBFBFF;
}

#post{
  width: 1000px;
  margin: auto;
  text-align: center;
  margin-top: 25px;
  margin-bottom: 25px;
}

</style>

<body>
  <h1>
    <%= @blog.title %>
  </h1>

  <% if admin_signed_in? %>
    <h1>
      <a class="btn btn-secondary"<%= link_to 'Edit', edit_blog_path(@blog) %></a>
      <a class="btn btn-secondary"<%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </h1>
  <% end %>

  <h3 id=post>
      <%= @blog.description %>
  </h3>

</body>
<%= render 'bottom_bar'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>